name = "rh-army-reviews1"
compatibility_date = "2026-09-20"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "rh-army-reviews-db"
database_id = "dcd34ad9-1fe7-4965-808e-315b0d0c0a14"
